const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Behaviors.Anchor,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Acts.AddVar
	];
};
self.C3_JsPropNameTable = [
	{фон: 0},
	{меню: 0},
	{играть: 0},
	{инструкция: 0},
	{иструкция: 0},
	{ходьба: 0},
	{поражение: 0},
	{тыПроиграл: 0},
	{победа: 0},
	{тыВыйграл: 0},
	{фонПодзем: 0},
	{Твёрдый: 0},
	{стенка: 0},
	{"8Направлений": 0},
	{СледитьЗа: 0},
	{рыцарь: 0},
	{Синусоида: 0},
	{враг: 0},
	{фон2Уровень: 0},
	{Якорь: 0},
	{СЧЕТ: 0},
	{Мышь: 0},
	{Пуля: 0},
	{стрела: 0},
	{фон3Уровень: 0},
	{последний: 0},
	{телепортНа3Лвл: 0},
	{телепортНа2Лвл: 0},
	{монета: 0},
	{кентавр: 0},
	{Спрайт: 0},
	{Спрайт2: 0},
	{Текст: 0},
	{менюшка: 0},
	{счет: 0}
];

self.InstanceType = {
	фон: class extends self.ITiledBackgroundInstance {},
	меню: class extends self.ITextInstance {},
	играть: class extends self.IButtonInstance {},
	инструкция: class extends self.IButtonInstance {},
	иструкция: class extends self.ITextInstance {},
	ходьба: class extends self.ITextInstance {},
	поражение: class extends self.ITextInstance {},
	тыПроиграл: class extends self.ITextInstance {},
	победа: class extends self.ITextInstance {},
	тыВыйграл: class extends self.ITextInstance {},
	фонПодзем: class extends self.ISpriteInstance {},
	стенка: class extends self.ISpriteInstance {},
	рыцарь: class extends self.ISpriteInstance {},
	враг: class extends self.ISpriteInstance {},
	фон2Уровень: class extends self.ISpriteInstance {},
	СЧЕТ: class extends self.ITextInstance {},
	Мышь: class extends self.IInstance {},
	стрела: class extends self.ISpriteInstance {},
	фон3Уровень: class extends self.ISpriteInstance {},
	последний: class extends self.ISpriteInstance {},
	телепортНа3Лвл: class extends self.ISpriteInstance {},
	телепортНа2Лвл: class extends self.ISpriteInstance {},
	монета: class extends self.ISpriteInstance {},
	кентавр: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	менюшка: class extends self.IButtonInstance {}
}